name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78a5c13846856305f44f76028b268445bf4e110a9c5d10abe292b862a9fbac52"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
