name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44580a9573687a7db8526b90217532929d7510df027b8f835ec3ff42c97023c1"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
