name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac0fd44454cafc7a4ae80c3c1cc9df5741807add636e47da2655c00106b629d9"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
