name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e22e8d166adc73738f9d7391eb94c7f06d16c18e2a2bb3f2c9eb8588e5ca12c5"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
