name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f1533a3884d56d94195f1f45fc23d8d89e005b415d3b900cf145740266bb837"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
