name: Update Minecraft version
description: Update modpack to a new Minecraft version, updating any mods along the way

inputs:
  working-directory:
    description: Directory to run packwiz in
    required: false
    default: "."
  minecraft-version:
    description: Minecraft version to update to
    required: true

outputs:
  is-update:
    description: Whether there are updates in the pack
  changelog-body:
    description: Text to include in the changelog
  pr-body:
    description: Text to include in the pull request body

runs:
  using: "node20"
  main: "index.js"
