name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea44625b15bfe98e2b3038b6c0ca6da5a69ea730f7bafc599a0003a4190f525f"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
