name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "673240362f9da84688d84352f3a661d49aa2ab152f6511bb7cb1fa0f53503f4c"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
