name: Build pack
description: Build a modpack

inputs:
  directory:
    description: Pack version directory
    required: true
  version-override:
    description: Force version
    required: false
    default: "null"

outputs:
  files:
    description: Files to include in the pack
    value: ${{ steps.files.outputs.files }}

runs:
  using: composite
  steps:
    - name: Cache packwiz
      uses: actions/cache@v4
      with:
        key: packwiz-${{ inputs.directory }}-${{ hashFiles(format('{0}/pack.toml', inputs.directory)) }}
        restore-keys: |
          packwiz-${{ inputs.directory }}-
        path: |
          ~/.cache/packwiz/cache

    - name: Setup Packwiz
      uses: "./.github/actions/setup-packwiz"

    - name: Ensure Packwiz index is updated
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: |
        packwiz refresh
        git diff --exit-code index.toml

    - name: Override modpack version with release version
      if: inputs.version-override != 'null'
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: |
        sed -i -e '/version =/ s/= .*/= "v'"${{ inputs.version-override }}"'"/' pack.toml

    - name: Build modpack
      shell: bash
      run: |
        packwiz --pack-file ${{ inputs.directory }}/pack.toml mr export -o "secrets-pack.mrpack"
        zip -r "source-code.zip" ${{ inputs.directory }}

    - name: Get build files
      id: files
      shell: bash
      run: |
        {
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)

          echo "files<<$EOF"
          echo secrets-pack.mrpack
          echo source-code.zip
          echo $EOF
        } >> "$GITHUB_OUTPUT"
