name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c73ace4af1de379e034de2981f47be669048f8a885b1af216f7e5b00ad12cd9"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
