name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "168c401c4983bf31d8a01bff954980dd2c455fb76b61cb5bf1dea084a8b762be"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
