name = "secret's pack"
author = "secret_online"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "079a5659be93a6da5257331f9c06dd90d241302315a9f79f0c6bf074d00a441c"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
