name: Build & Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  get-build-matrix:
    name: Get build matrix
    runs-on: ubuntu-latest
    outputs:
      has-builds: ${{ steps.build-matrix.outputs.has-builds }}
      build-matrix: ${{ steps.build-matrix.outputs.build-matrix }}
      has-tests: ${{ steps.build-matrix.outputs.has-tests }}
      test-modpack-matrix: ${{ steps.build-matrix.outputs.test-modpack-matrix }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Install
        run: |
          npm ci

      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@v47

      - name: Get build matrix
        id: build-matrix
        uses: ./.github/actions/get-build-matrix
        with:
          changed-files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}

  build-packs:
    name: ${{ matrix.build-matrix.title }}
    runs-on: ubuntu-latest
    needs:
      - get-build-matrix
    if: needs.get-build-matrix.outputs.has-builds == 'true'
    strategy:
      matrix:
        build-matrix: ${{ fromJson(needs.get-build-matrix.outputs.build-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Setup Packwiz
        uses: SecretOnline/minecraft-actions/setup-packwiz@v2

      - name: Ensure Packwiz index is updated
        working-directory: ${{ matrix.build-matrix.directory }}
        shell: bash
        run: |
          packwiz refresh
          git diff --exit-code index.toml

      - name: Build modpack
        shell: bash
        run: |
          packwiz --pack-file ${{ matrix.build-matrix.directory }}/pack.toml mr export -o "secrets-pack.mrpack"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: secrets-pack.${{ matrix.build-matrix.directory }}
          path: secrets-pack.mrpack
          retention-days: 1

  test-modpack:
    name: ${{ matrix.test-matrix.title }}
    runs-on: ubuntu-latest
    needs:
      - get-build-matrix
      - build-packs
    permissions:
      contents: read
      pull-requests: write
    if: needs.get-build-matrix.outputs.has-tests == 'true'
    strategy:
      matrix:
        # Type:
        # { type: "modpack" | "resourcepack" | "datapack"; pack: string; directory: string; client: "modded" | "vanilla" | "false"; server: "modded" | "vanilla" | "false"; }
        test-matrix: ${{ fromJson(needs.get-build-matrix.outputs.test-modpack-matrix) }}
      fail-fast: false
    steps:
      - name: Install apt packages
        run: sudo apt-get update && sudo apt-get install -y xvfb libgl1-mesa-dri mesa-utils imagemagick

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: secrets-pack.${{ matrix.test-matrix.directory }}

      - name: Get Minecraft version from pack
        id: get-minecraft-version
        run: |
          unzip -jo secrets-pack.mrpack modrinth.index.json

          minecraft_version=$(cat modrinth.index.json | jq --raw-output '.dependencies.minecraft')
          echo "minecraft-version=$minecraft_version" >> "$GITHUB_OUTPUT"

          version_url=$(curl -s https://piston-meta.mojang.com/mc/game/version_manifest_v2.json | jq --raw-output ".versions | map(select(.id == \"$minecraft_version\"))[0].url")
          java_version=$(curl -s "$version_url" | jq --raw-output '.javaVersion.majorVersion')
          echo "java-version=$java_version" >> "$GITHUB_OUTPUT"

          rm modrinth.index.json

      - name: Setup Java ${{ steps.get-minecraft-version.outputs.java-version }}
        id: setup-java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.get-minecraft-version.outputs.java-version }}
          distribution: zulu

      - name: Setup server
        if: matrix.test-matrix.server != 'false'
        uses: SecretOnline/minecraft-actions/setup-mc-server@v2
        with:
          server-directory: server
          minecraft-version: ${{ steps.get-minecraft-version.outputs.minecraft-version }}
          loader: fabric
          accept-eula: true

      - name: Setup client
        if: matrix.test-matrix.client != 'false'
        uses: SecretOnline/minecraft-actions/setup-mc-client@v2
        with:
          client-directory: client
          minecraft-version: ${{ steps.get-minecraft-version.outputs.minecraft-version }}
          loader: fabric

      - name: Install modpack to server
        if: matrix.test-matrix.server != 'false' && matrix.test-matrix.server != 'vanilla'
        uses: SecretOnline/minecraft-actions/unpack-mrpack@v2
        with:
          mrpack-file: secrets-pack.mrpack
          minecraft-directory: server
          environment: server

      - name: Install modpack to client
        if: matrix.test-matrix.client != 'false' && matrix.test-matrix.client != 'vanilla'
        uses: SecretOnline/minecraft-actions/unpack-mrpack@v2
        with:
          mrpack-file: secrets-pack.mrpack
          minecraft-directory: client
          environment: client

      - name: Customise client
        working-directory: client
        continue-on-error: true
        timeout-minutes: 11
        if: matrix.test-matrix.client != 'false'
        run: |
          # Disable shaders because rendering is too slow without accelerated graphics
          mkdir -p config
          cat <<EOF > config/iris.properties
          shaderPack=
          EOF

          # Remove Voxy as the environment in GitHub Actions doesn't support some of its rendering
          rm -f mods/voxy-*

      - name: Run server
        id: run-server
        if: matrix.test-matrix.server != 'false'
        uses: SecretOnline/minecraft-actions/run-mc-server@v2
        with:
          server-directory: server
          log-file: server/server.log

      - name: Run client
        if: matrix.test-matrix.client != 'false'
        id: run-client
        uses: SecretOnline/minecraft-actions/run-mc-client@v2
        with:
          client-directory: client
          log-file: client/client.log
          width: 854
          height: 480
          server-address: ${{matrix.test-matrix.server == 'false' && '' || 'localhost:25565'}}
          singleplayer-world: ${{matrix.test-matrix.server == 'false' && 'world' || ''}}

      - name: Wait for client to fully join
        if: matrix.test-matrix.client != 'false'
        run: |
          sleep 30

      - name: Screenshot Minecraft client
        id: screenshot
        if: matrix.test-matrix.client != 'false'
        uses: SecretOnline/minecraft-actions/screenshot-mc-client@v2
        with:
          display: ${{ steps.run-client.outputs.display }}
          xauthority: ${{ steps.run-client.outputs.xauthority }}
          artifact-name: client-screenshot-${{ matrix.test-matrix.directory }}
          add-job-summary: "true"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: test-logs-${{ matrix.test-matrix.directory }}-${{ matrix.test-matrix.server }}-${{ matrix.test-matrix.client }}
          path: |
            client/client.log
            client/logs/*
            server/server.log
            server/logs/*
          retention-days: 7

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v3
        if: github.event_name == 'pull_request' && matrix.test-matrix.client != 'false'
        with:
          message-id: "modpack-test-client-secrets-pack-${{ matrix.test-matrix.directory }}"
          message: |
            ## ${{ matrix.test-matrix.title }} screenshot

            ![client-screenshot-${{ matrix.test-matrix.directory }}](${{ steps.screenshot.outputs.url }})
