name: Deploy
run-name: Deploy v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      is-release:
        description: Publish release
        required: true
        type: boolean
      version:
        description: Pack version (no v prefix)
        required: true
        type: string

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: Setup Packwiz
        uses: SecretOnline/minecraft-actions/setup-packwiz@v2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Install
        run: |
          npm ci

      - name: Get deploy info
        id: deploy-info
        uses: ./.github/actions/get-deploy-info
        with:
          version: ${{ inputs.version }}

      - name: Ensure Packwiz index is updated
        working-directory: ${{ steps.deploy-info.outputs.directory }}
        shell: bash
        run: |
          packwiz refresh
          git diff --exit-code index.toml

      - name: Override modpack version with release version
        working-directory: ${{ steps.deploy-info.outputs.directory }}
        shell: bash
        run: |
          sed -i -e '/version =/ s/= .*/= "v'"${{ inputs.version }}"'"/' pack.toml

      - name: Build modpack
        shell: bash
        run: |
          packwiz --pack-file ${{ steps.deploy-info.outputs.directory }}/pack.toml mr export -o "secrets-pack.${{ inputs.version }}.mrpack"

      - name: Parse changelog
        id: changelog
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: v${{ inputs.version }}
          changelog: CHANGELOG.md

      - name: Print release details
        run: |
          echo "name: ${{ steps.deploy-info.outputs.release-name }}"
          echo "version: v${{ inputs.version }}"
          echo "game-versions: ${{ steps.deploy-info.outputs.game-versions }}"
          echo "changelog: ${{ steps.changelog.outputs.release-notes }}"
          echo "loaders: ${{ steps.deploy-info.outputs.loaders }}"
          echo "modrinth-id: ${{ steps.deploy-info.outputs.modrinth-id }}"

      - name: Create Modrinth Release
        if: inputs.is-release && steps.deploy-info.outputs.modrinth-id != ''
        id: modrinth-release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ steps.deploy-info.outputs.release-name }}
          version: v${{ inputs.version }}
          game-versions: ${{ steps.deploy-info.outputs.game-versions }}
          changelog: ${{ steps.changelog.outputs.release-notes }}
          loaders: ${{ steps.deploy-info.outputs.loaders }}
          files: secrets-pack.${{ inputs.version }}.mrpack
          modrinth-id: ${{ steps.deploy-info.outputs.modrinth-id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

      - name: Update Modrinth description
        if: inputs.is-release && steps.deploy-info.outputs.modrinth-id != ''
        uses: funnyboy-roks/modrinth-auto-desc@v1.7
        with:
          auth-token: ${{ secrets.MODRINTH_TOKEN }}
          slug: ${{ steps.deploy-info.outputs.modrinth-id }}
          readme: README.md

      - name: Create GitHub release
        if: inputs.is-release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ inputs.version }}
          name: ${{ steps.deploy-info.outputs.release-name }}
          body: ${{ steps.changelog.outputs.release-notes }}
          files: secrets-pack.${{ inputs.version }}.mrpack
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post release to Discord
        if: inputs.is-release
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: ${{ steps.deploy-info.outputs.pack-name }} Releases
          avatar-url: ${{ steps.deploy-info.outputs.pack-icon-url }}
          content: |
            ${{ steps.deploy-info.outputs.release-name }} has been released!
            https://modrinth.com/modpack/secrets-pack/version/v${{ inputs.version }}
